AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - test/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false  
